name: Install Node Dependencies, Build Docker Image, Push and Release a Docker container to Heroku

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integrate-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build --if-present

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: server
